name: dice
version: 2.0.0
author: Lars Tackmann <lars@solvr.io>
description: Lightweight dependency injection framework for Dart.
homepage: https://github.com/ltackmann/dice

environment:
  sdk: '>=2.0.0'

dependencies:
  logging: any

dev_dependencies:
  #browser: ^0.10.0

  #logging_handlers: any
  console_log_handler: any

  test: ^1.2.0
